name: sa_sqflite_lego
description: "sqflite lego under simple architecture framework."
#publish_to: 'none'
repository: https://github.com/flutter-lego/sa_sqflite_lego

version: 1.0.5

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: #@add
  gap: #@add
  june_flow_util:
  styled_widget: #@add
  modal_bottom_sheet: #@add
  keyboard_attachable: #@add
  flutter_zoom_drawer: #@add
  flutter_screenutil:
  bot_toast:
  sqflite: #@add
  path: #@add
  orange:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:
  screenutil_lego: #@add
  bot_toast_lego: #@add
  sa_data_class_lego:
  sa_enum_lego:
  orange_lego: #@add
  widget_binding_lego: #@add

flutter:
  assets:
    - assets/lego/sa_sqflite_lego/
  uses-material-design: true

topics:
  - lego